name: Ngrok RDP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and extract Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Authenticate with Ngrok
      env:
        NGROK_AUTH_TOKEN: 2S1tGwgj12MGLNqsoeMMQ6nPxdn_3PUaNy8kwXJZ2UJqQ2reX
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN

    - name: Start Ngrok RDP tunnel
      run: ./ngrok tcp 3389
